# Code Generated by Sidekick is for learning and experimentation purposes only. | filename: coder-reviewer-swarm.py
from __future__ import annotations

import ast
import hashlib
import math
import operator
import os
import re
from pathlib import Path
from textwrap import dedent
from typing import Annotated, TypedDict

import chromadb
from langgraph.graph import END, START, StateGraph

ROOT = Path.cwd()
REPO_DIR = ROOT / "mock_buggy_repo"
CHROMA_DIR = ROOT / "chroma_db"
FEATURE_REQUEST_FILE = ROOT / "feature_request.txt"
GUIDELINES_FILE = ROOT / "architecture_guidelines.md"
OUTPUT_FILE = ROOT / "generated_feature.py"
COLLECTION_NAME = "mock_buggy_repo_chunks"
MAX_ITERATIONS = int(os.getenv("MAX_ITERATIONS", "3"))

if MAX_ITERATIONS < 2:
    raise ValueError("MAX_ITERATIONS must be at least 2.")


class SwarmState(TypedDict):
    feature_request: str
    architecture_guidelines: str
    rag_context: list[str]
    iteration: int
    max_iterations: int
    candidate_code: str
    review_status: str
    review_feedback: str
    coder_prompt: str
    escalation_reason: str
    trace: Annotated[list[str], operator.add]


def write_file(path: Path, content: str, only_if_missing: bool = False) -> None:
    if only_if_missing and path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dedent(content).lstrip(), encoding="utf-8")


def bootstrap_workspace() -> None:
    """Create the mock repository before building the swarm."""
    REPO_DIR.mkdir(parents=True, exist_ok=True)

    write_file(REPO_DIR / "__init__.py", '"""Mock repository used for RAG retrieval."""\n')

    write_file(
        REPO_DIR / "validation.py",
        """
        def normalize_email(email: str) -> str:
            value = email.strip().lower()
            if "@" not in value:
                raise ValueError("email must contain @")
            return value
        """,
    )

    write_file(
        REPO_DIR / "user_store.py",
        """
        USERS_BY_EMAIL: dict[str, dict[str, str]] = {
            "ana@example.com": {"id": "u-100", "name": "Ana"},
            "sam@example.com": {"id": "u-200", "name": "Sam"},
        }

        def get_user_by_email(normalized_email: str) -> dict[str, str] | None:
            # Intentional repository behavior: callers must normalize first.
            return USERS_BY_EMAIL.get(normalized_email)
        """,
    )

    write_file(
        FEATURE_REQUEST_FILE,
        """
        Implement `find_user_by_email(email: str) -> dict[str, str] | None` in
        `generated_feature.py`. Reuse the repository's validation and lookup helpers;
        do not directly access storage.
        """,
        only_if_missing=True,
    )

    write_file(
        GUIDELINES_FILE,
        """
        # Architecture Guidelines

        The generated module must reuse repository helpers and avoid direct storage access.

        - REQUIRED: def find_user_by_email(email: str) -> dict[str, str] | None:
        - REQUIRED: from mock_buggy_repo.validation import normalize_email
        - REQUIRED: normalized_email = normalize_email(email)
        - REQUIRED: from mock_buggy_repo.user_store import get_user_by_email
        - REQUIRED: return get_user_by_email(normalized_email)
        - FORBIDDEN: USERS_BY_EMAIL
        - FORBIDDEN: .lower(
        """,
        only_if_missing=True,
    )


class StableHashEmbedding:
    """Small offline embedding function for deterministic local RAG."""

    dimensions = 192

    def __call__(self, input: list[str]) -> list[list[float]]:
        return [self._embed(text) for text in input]

    def name(self) -> str:
        return "stable_hash_embedding_v1"

    def get_config(self) -> dict[str, int]:
        return {"dimensions": self.dimensions}

    def _embed(self, text: str) -> list[float]:
        vector = [0.0] * self.dimensions
        for token in re.findall(r"[A-Za-z_]\w*", text.lower()):
            digest = hashlib.sha256(token.encode("utf-8")).digest()
            slot = int.from_bytes(digest[:4], "big") % self.dimensions
            vector[slot] += 1.0 if digest[4] % 2 else -1.0
        norm = math.sqrt(sum(value * value for value in vector)) or 1.0
        return [value / norm for value in vector]


def chunk_text(text: str, size: int = 700, overlap: int = 100) -> list[str]:
    chunks, start = [], 0
    while start < len(text):
        end = min(start + size, len(text))
        chunks.append(text[start:end])
        if end == len(text):
            break
        start = end - overlap
    return chunks


def index_repository():
    client = chromadb.PersistentClient(path=str(CHROMA_DIR))
    collection = client.get_or_create_collection(
        name=COLLECTION_NAME,
        embedding_function=StableHashEmbedding(),
    )

    documents, metadatas, ids = [], [], []
    for source in sorted(REPO_DIR.glob("*.py")):
        for index, chunk in enumerate(chunk_text(source.read_text(encoding="utf-8"))):
            documents.append(chunk)
            metadatas.append({"source": source.name, "chunk": index})
            ids.append(f"{source.stem}-{index}")

    collection.upsert(ids=ids, documents=documents, metadatas=metadatas)
    return collection, len(documents)


def retrieve_context(collection, query: str, top_k: int = 3) -> list[str]:
    result = collection.query(
        query_texts=[query],
        n_results=min(top_k, collection.count()),
        include=["documents", "metadatas"],
    )
    documents = result["documents"][0]
    metadatas = result["metadatas"][0]
    return [
        f"Source: {metadata['source']} (chunk {metadata['chunk']})\n{document}"
        for document, metadata in zip(documents, metadatas)
    ]


def render_coder_prompt(state: SwarmState) -> str:
    memory = "\n\n".join(state["rag_context"])
    feedback = state["review_feedback"] or "None — initial implementation."
    return dedent(
        f"""
        You are the Coder agent.

        FEATURE REQUEST:
        {state["feature_request"]}

        RAG MEMORY:
        {memory}

        REVIEW FEEDBACK TO APPLY:
        {feedback}

        Write only the implementation for generated_feature.py.
        """
    ).strip()


def draft_candidate(coder_prompt: str, attempt: int) -> str:
    """Deterministic demo coder to guarantee a visible reject-and-retry trace."""
    if "find_user_by_email" not in coder_prompt or "get_user_by_email" not in coder_prompt:
        raise RuntimeError("Feature request or RAG memory was not injected into the Coder prompt.")

    initial_candidate = dedent(
        """
        from mock_buggy_repo.user_store import get_user_by_email

        def find_user_by_email(email: str) -> dict[str, str] | None:
            return get_user_by_email(email)
        """
    ).lstrip()

    corrected_candidate = dedent(
        """
        from mock_buggy_repo.user_store import get_user_by_email
        from mock_buggy_repo.validation import normalize_email

        def find_user_by_email(email: str) -> dict[str, str] | None:
            normalized_email = normalize_email(email)
            return get_user_by_email(normalized_email)
        """
    ).lstrip()

    if attempt == 1:
        return initial_candidate
    if "REJECTED:" not in coder_prompt:
        raise RuntimeError("Retry was attempted without injected Reviewer feedback.")
    return corrected_candidate


def coder_agent(state: SwarmState) -> dict:
    attempt = state["iteration"] + 1
    coder_prompt = render_coder_prompt(state)
    candidate = draft_candidate(coder_prompt, attempt)
    OUTPUT_FILE.write_text(candidate, encoding="utf-8")

    feedback_flag = "yes" if state["review_feedback"] else "no"
    return {
        "iteration": attempt,
        "candidate_code": candidate,
        "coder_prompt": coder_prompt,
        "trace": [
            f"CODER | attempt={attempt} | rag_chunks={len(state['rag_context'])} "
            f"| feedback_injected={feedback_flag} | wrote={OUTPUT_FILE.name}"
        ],
    }


def guideline_markers(guidelines: str, marker_type: str) -> list[str]:
    return [
        line.split(f"{marker_type}:", 1)[1].strip()
        for line in guidelines.splitlines()
        if f"{marker_type}:" in line
    ]


def destination(verdict: str, iteration: int, max_iterations: int) -> str:
    if verdict == "APPROVED":
        return END
    if iteration >= max_iterations:
        return "escalate"
    return "coder"


def reviewer_agent(state: SwarmState) -> dict:
    candidate = state["candidate_code"]
    required = guideline_markers(state["architecture_guidelines"], "REQUIRED")
    forbidden = guideline_markers(state["architecture_guidelines"], "FORBIDDEN")
    missing = [marker for marker in required if marker not in candidate]
    forbidden_hits = [marker for marker in forbidden if marker in candidate]
    issues = []

    try:
        ast.parse(candidate)
    except SyntaxError as error:
        issues.append(f"syntax error at line {error.lineno}: {error.msg}")

    if missing:
        issues.append("missing required markers: " + "; ".join(missing))
    if forbidden_hits:
        issues.append("forbidden markers found: " + "; ".join(forbidden_hits))

    verdict = "APPROVED" if not issues else "REJECTED"
    feedback = (
        "APPROVED: all guideline checks passed."
        if not issues
        else "REJECTED: " + " | ".join(issues)
    )
    next_step = destination(verdict, state["iteration"], state["max_iterations"])
    route_label = "END" if next_step == END else next_step

    return {
        "review_status": verdict,
        "review_feedback": feedback,
        "trace": [
            f"REVIEWER | attempt={state['iteration']} | verdict={verdict} "
            f"| route={route_label} | feedback={feedback}"
        ],
    }


def route_after_review(state: SwarmState) -> str:
    return destination(
        state["review_status"],
        state["iteration"],
        state["max_iterations"],
    )


def escalation_agent(state: SwarmState) -> dict:
    reason = (
        f"Escalated after {state['iteration']} attempts. "
        f"Last review feedback: {state['review_feedback']}"
    )
    return {
        "review_status": "ESCALATED",
        "escalation_reason": reason,
        "trace": [f"ESCALATION | {reason}"],
    }


def build_swarm():
    workflow = StateGraph(SwarmState)
    workflow.add_node("coder", coder_agent)
    workflow.add_node("reviewer", reviewer_agent)
    workflow.add_node("escalate", escalation_agent)
    workflow.add_edge(START, "coder")
    workflow.add_edge("coder", "reviewer")
    workflow.add_conditional_edges(
        "reviewer",
        route_after_review,
        {"coder": "coder", "escalate": "escalate", END: END},
    )
    workflow.add_edge("escalate", END)
    return workflow.compile()


def merge_update(state: dict, update: dict) -> None:
    for key, value in update.items():
        if key == "trace":
            state["trace"].extend(value)
        else:
            state[key] = value


def run_swarm(swarm, initial_state: SwarmState) -> dict:
    final_state = dict(initial_state)
    for event in swarm.stream(initial_state, stream_mode="updates"):
        for update in event.values():
            merge_update(final_state, update)
            for message in update.get("trace", []):
                print(f"TRACE | {message}")
    return final_state


def main() -> None:
    bootstrap_workspace()
    collection, indexed_chunks = index_repository()
    feature_request = FEATURE_REQUEST_FILE.read_text(encoding="utf-8").strip()
    guidelines = GUIDELINES_FILE.read_text(encoding="utf-8").strip()
    rag_context = retrieve_context(collection, feature_request)

    if not feature_request:
        raise ValueError("feature_request.txt must not be empty.")

    print(f"TRACE | BOOTSTRAP | repo={REPO_DIR.name} | source_files={len(list(REPO_DIR.glob('*.py')))}")
    print(
        f"TRACE | RAG | indexed_chunks={indexed_chunks} | retrieved_chunks={len(rag_context)} "
        "| injected_into_initial_state=yes"
    )

    initial_state: SwarmState = {
        "feature_request": feature_request,
        "architecture_guidelines": guidelines,
        "rag_context": rag_context,
        "iteration": 0,
        "max_iterations": MAX_ITERATIONS,
        "candidate_code": "",
        "review_status": "PENDING",
        "review_feedback": "",
        "coder_prompt": "",
        "escalation_reason": "",
        "trace": [],
    }

    final_state = run_swarm(build_swarm(), initial_state)
    print(
        f"TRACE | FINAL | status={final_state['review_status']} "
        f"| iterations={final_state['iteration']}/{MAX_ITERATIONS} "
        f"| generated={OUTPUT_FILE.name}"
    )


if __name__ == "__main__":
    main()
