# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: jira-langgraph-rubric-pipeline.py

import os
import subprocess
import tempfile
from typing import Literal, TypedDict

from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph


MAX_RETRIES = 3
MODEL = ChatOpenAI(
    model=os.getenv("OPENAI_MODEL", "gpt-4.1-mini"),
    temperature=0,
)


class JiraState(TypedDict, total=False):
    ticket: str
    plan: str
    code: str
    tests: str
    error: str | None
    retry_count: int
    workdir: str
    status: str


def clean_response(content: object) -> str:
    text = str(content).strip()
    lines = text.splitlines()
    return "\n".join(
        line for line in lines
        if not line.strip().startswith("```")
    ).strip()


def planner(state: JiraState) -> JiraState:
    print("[PLANNER] Creating implementation plan")

    prompt = f"""
You are the Planner for a Jira implementation ticket.

Jira ticket:
{state["ticket"]}

Create a numbered implementation plan.
Do not write code, pseudocode, function bodies, or code snippets.
Describe:
1. Required behavior
2. Components and functions
3. Validation and edge cases
4. Testable acceptance criteria
"""

    response = MODEL.invoke(prompt)
    return {
        "plan": clean_response(response.content),
        "retry_count": 0,
        "error": None,
        "workdir": tempfile.mkdtemp(prefix="jira-pipeline-"),
        "status": "PLANNED",
    }


def coder(state: JiraState) -> JiraState:
    print(f"[CODER] Generating implementation, attempt {state['retry_count'] + 1}")

    retry_context = state.get("error") or "No previous failure."
    prompt = f"""
You are the Coder for a Jira implementation pipeline.

Jira ticket:
{state["ticket"]}

Approved implementation plan:
{state["plan"]}

Current attempt:
{state["retry_count"] + 1} of {MAX_RETRIES}

Previous compiler or test failure:
{retry_context}

Write the complete contents of solution.py.
Return Python source only, without markdown fences.
Use the standard library unless the ticket requires another dependency.
Correct the previous failure rather than ignoring it.
"""

    response = MODEL.invoke(prompt)
    return {
        "code": clean_response(response.content),
        "status": "CODE_GENERATED",
    }


def compiler(state: JiraState) -> JiraState:
    print("[COMPILER] Compiling generated implementation")

    solution_path = os.path.join(state["workdir"], "solution.py")
    with open(solution_path, "w", encoding="utf-8") as file:
        file.write(state["code"] + "\n")

    result = subprocess.run(
        ["python", "-m", "py_compile", "solution.py"],
        cwd=state["workdir"],
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )

    if result.returncode != 0:
        error = (
            "COMPILER FAILURE\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )
        return {"error": error, "status": "COMPILE_FAILED"}

    # Successful compilation clears any prior retry error.
    return {
        "error": None,
        "status": "COMPILED",
    }


def test_runner(state: JiraState) -> JiraState:
    print("[TEST_RUNNER] Generating and running pytest tests")

    prompt = f"""
You are the Test Runner for a Jira implementation pipeline.

Jira ticket:
{state["ticket"]}

Implementation plan:
{state["plan"]}

Actual generated solution.py:
{state["code"]}

Write complete pytest tests for the actual generated implementation above.
Test the Jira acceptance criteria, normal behavior, edge cases, and invalid
inputs where relevant. Import functions from solution.py.
Return only test source code, without markdown fences.
Do not create generic placeholder tests.
"""

    response = MODEL.invoke(prompt)
    tests = clean_response(response.content)

    test_path = os.path.join(state["workdir"], "test_solution.py")
    with open(test_path, "w", encoding="utf-8") as file:
        file.write(tests + "\n")

    result = subprocess.run(
        ["pytest", "-q", "test_solution.py"],
        cwd=state["workdir"],
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )

    if result.returncode != 0:
        error = (
            "TEST FAILURE\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )
        return {
            "tests": tests,
            "error": error,
            "status": "TESTS_FAILED",
        }

    # Successful tests clear the retry error.
    return {
        "tests": tests,
        "error": None,
        "status": "TESTS_PASSED",
    }


def error_handler(state: JiraState) -> JiraState:
    next_retry_count = state["retry_count"] + 1
    print(
        f"[ERROR_HANDLER] Retry {next_retry_count}/{MAX_RETRIES}: "
        f"{state.get('error', 'unknown error').splitlines()[0]}"
    )

    return {
        "retry_count": next_retry_count,
        "status": "RETRYING",
    }


def should_retry(
    state: JiraState,
) -> Literal["error_handler", "test_runner", "end"]:
    """
    Compile failures go to error_handler.
    Successful compilation proceeds to test_runner.
    Test failures are routed through this same retry decision.
    """
    if state["status"] == "COMPILED":
        return "test_runner"

    if state.get("error") and state["retry_count"] < MAX_RETRIES:
        return "error_handler"

    return "end"


def should_retry_after_tests(
    state: JiraState,
) -> Literal["error_handler", "end"]:
    if state["status"] == "TESTS_PASSED":
        return "end"

    if state.get("error") and state["retry_count"] < MAX_RETRIES:
        return "error_handler"

    return "end"


def build_graph():
    graph = StateGraph(JiraState)

    # Required five nodes.
    graph.add_node("planner", planner)
    graph.add_node("coder", coder)
    graph.add_node("compiler", compiler)
    graph.add_node("error_handler", error_handler)
    graph.add_node("test_runner", test_runner)

    graph.add_edge(START, "planner")
    graph.add_edge("planner", "coder")
    graph.add_edge("coder", "compiler")

    # Compiler success proceeds to tests; compiler failure retries or ends.
    graph.add_conditional_edges(
        "compiler",
        should_retry,
        {
            "test_runner": "test_runner",
            "error_handler": "error_handler",
            "end": END,
        },
    )

    # Test failures reuse the same error_handler → coder loop.
    graph.add_conditional_edges(
        "test_runner",
        should_retry_after_tests,
        {
            "error_handler": "error_handler",
            "end": END,
        },
    )

    graph.add_edge("error_handler", "coder")

    return graph.compile()


def run_ticket(ticket: str) -> JiraState:
    app = build_graph()
    return app.invoke(
        {
            "ticket": ticket,
            "retry_count": 0,
            "error": None,
        }
    )


if __name__ == "__main__":
    jira_ticket = os.getenv(
        "JIRA_TICKET",
        (
            "Implement normalize_email(value: str) -> str. "
            "Trim whitespace, lowercase the address, and reject values "
            "without exactly one '@' character."
        ),
    )

    final_state = run_ticket(jira_ticket)

    print("\n[PIPELINE] Final status:", final_state["status"])
    print("[PIPELINE] Retry count:", final_state["retry_count"])
    print("[PIPELINE] Workspace:", final_state["workdir"])

    if final_state.get("error"):
        print("\n[PIPELINE] Final error:\n")
        print(final_state["error"])
    else:
        print("\n[PIPELINE] Implementation and tests passed.")
