# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: test_podman_code_runner.py
from pathlib import Path

from podman_code_runner import PodmanCodeRunner


class FakeImages:
    def __init__(self):
        self.builds = 0
        self.fail = False

    def pull(self, image):
        if self.fail:
            raise RuntimeError("service unavailable")

    def build(self, *, path, tag, **kwargs):
        assert (Path(path) / "app.py").is_file()
        self.builds += 1
        return object(), []


class FakeContainer:
    def __init__(self, exit_code=0, running=False, stdout=b"", stderr=b""):
        self.exit_code = exit_code
        self.running = running
        self.stdout = stdout
        self.stderr = stderr
        self.killed = False
        self.removed = False

    def start(self):
        pass

    def inspect(self):
        return {"State": {"Running": self.running, "ExitCode": self.exit_code}}

    def logs(self, stdout=False, stderr=False):
        return self.stdout if stdout else self.stderr

    def kill(self):
        self.killed = True
        self.running = False

    def remove(self, force=False):
        self.removed = True


class FakeContainers:
    def __init__(self, container):
        self.container = container
        self.options = None

    def create(self, **options):
        self.options = options
        return self.container


class FakeClient:
    def __init__(self, container):
        self.images = FakeImages()
        self.containers = FakeContainers(container)
        self.closed = False

    def close(self):
        self.closed = True


class FakeClock:
    def __init__(self):
        self.value = 0.0

    def now(self):
        return self.value

    def sleep(self, seconds):
        self.value += seconds


def test_success_applies_controls_builds_image_and_cleans_up():
    container = FakeContainer(stdout=b"3628800\n")
    client = FakeClient(container)
    runner = PodmanCodeRunner(client_factory=lambda: client)

    result = runner.run("import math\nprint(math.factorial(10))")

    assert result.success is True
    assert result.stdout == "3628800\n"
    assert client.images.builds == 1
    assert container.removed is True
    assert client.closed is True
    assert client.containers.options["network_mode"] == "none"
    assert client.containers.options["read_only"] is True
    assert client.containers.options["mem_limit"] <= 128 * 1024 * 1024
    assert client.containers.options["user"] == "65532:65532"
    assert client.containers.options["volumes"] == {}


def test_nonzero_exit_returns_stderr_without_building_image():
    container = FakeContainer(exit_code=1, stderr=b"RuntimeError: demonstration failure\n")
    client = FakeClient(container)

    result = PodmanCodeRunner(client_factory=lambda: client).run("raise RuntimeError()")

    assert result.success is False
    assert result.exit_code == 1
    assert "RuntimeError" in result.stderr
    assert client.images.builds == 0
    assert container.removed is True


def test_timeout_kills_and_removes_container_without_building_image():
    clock = FakeClock()
    container = FakeContainer(running=True)
    client = FakeClient(container)
    runner = PodmanCodeRunner(
        client_factory=lambda: client,
        clock=clock.now,
        sleeper=clock.sleep,
    )

    result = runner.run("while True:\n    pass", timeout=10)

    assert result.success is False
    assert result.timed_out is True
    assert result.exit_code == 124
    assert container.killed is True
    assert container.removed is True
    assert client.images.builds == 0


def test_invalid_request_and_podman_api_error_are_structured():
    container = FakeContainer()
    client = FakeClient(container)
    client.images.fail = True
    runner = PodmanCodeRunner(client_factory=lambda: client)

    invalid = runner.run("print(1)", timeout=9)
    api_error = runner.run("print(1)")

    assert invalid.exit_code == 2
    assert "Invalid run request" in invalid.stderr
    assert api_error.exit_code == 125
    assert "Podman API error" in api_error.stderr
