# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: podman_code_runner.py
from __future__ import annotations

import argparse
import os
import shutil
import tempfile
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, ValidationError

try:
    from podman import PodmanClient
except ImportError:
    PodmanClient = None

BASE_IMAGE = "docker.io/library/python:3.11.11-slim-bookworm"
REUSABLE_IMAGE = "student-sandbox-app:latest"
MEMORY_LIMIT_BYTES = 128 * 1024 * 1024
CPU_PERIOD = 100_000
CPU_QUOTA = 50_000
NON_ROOT_USER = "65532:65532"


class RunRequest(BaseModel):
    model_config = ConfigDict(strict=True)

    code: str = Field(min_length=1, max_length=65_536)
    timeout: int = Field(default=20, ge=10, le=60)


class RunResult(BaseModel):
    success: bool
    stdout: str
    stderr: str
    exit_code: int
    timed_out: bool


def safe_error(error: Exception) -> str:
    message = " ".join(str(error).split())
    return message[:300] or type(error).__name__


def validation_message(error: ValidationError) -> str:
    return "; ".join(
        f"{'.'.join(str(part) for part in item['loc'])}: {item['msg']}"
        for item in error.errors()
    )


def as_text(value: Any) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return str(value or "")


def append_error(existing: str, addition: str) -> str:
    return f"{existing.rstrip()}\n{addition}" if existing else addition


class PodmanCodeRunner:
    def __init__(
        self,
        *,
        endpoint: str | None = None,
        client_factory: Callable[[], Any] | None = None,
        clock: Callable[[], float] = time.monotonic,
        sleeper: Callable[[float], None] = time.sleep,
    ) -> None:
        self.endpoint = endpoint
        self._client_factory = client_factory
        self._clock = clock
        self._sleeper = sleeper

    def run(self, code: str, timeout: int = 20) -> RunResult:
        try:
            request = RunRequest.model_validate({"code": code, "timeout": timeout})
        except ValidationError as error:
            return RunResult(
                success=False,
                stdout="",
                stderr=f"Invalid run request: {validation_message(error)}",
                exit_code=2,
                timed_out=False,
            )

        client: Any | None = None
        container: Any | None = None
        try:
            client = self._new_client()
            client.images.pull(BASE_IMAGE)

            container = client.containers.create(**self._container_options(request))
            container.start()

            exit_code, timed_out = self._wait_for_exit(container, request.timeout)
            stdout, stderr = self._read_logs(container)

            if timed_out:
                return RunResult(
                    success=False,
                    stdout=stdout,
                    stderr=append_error(
                        stderr,
                        f"Execution timed out after {request.timeout} seconds.",
                    ),
                    exit_code=124,
                    timed_out=True,
                )

            if exit_code != 0:
                return RunResult(
                    success=False,
                    stdout=stdout,
                    stderr=stderr,
                    exit_code=exit_code,
                    timed_out=False,
                )

            try:
                self._build_reusable_image(client, request.code)
            except Exception as error:
                return RunResult(
                    success=False,
                    stdout=stdout,
                    stderr=append_error(
                        stderr,
                        f"Reusable image build failed: {safe_error(error)}",
                    ),
                    exit_code=125,
                    timed_out=False,
                )

            return RunResult(
                success=True,
                stdout=stdout,
                stderr=stderr,
                exit_code=0,
                timed_out=False,
            )
        except Exception as error:
            return RunResult(
                success=False,
                stdout="",
                stderr=f"Podman API error: {safe_error(error)}",
                exit_code=125,
                timed_out=False,
            )
        finally:
            if container is not None:
                try:
                    container.remove(force=True)
                except Exception:
                    pass
            if client is not None:
                try:
                    client.close()
                except Exception:
                    pass

    def _new_client(self) -> Any:
        if self._client_factory is not None:
            return self._client_factory()
        if PodmanClient is None:
            raise RuntimeError("The Podman Python bindings are not installed")

        endpoint = self.endpoint or os.getenv("PODMAN_HOST")
        return PodmanClient(base_url=endpoint) if endpoint else PodmanClient()

    def _container_options(self, request: RunRequest) -> dict[str, Any]:
        return {
            "image": BASE_IMAGE,
            "command": ["python", "-I", "-B", "-c", request.code],
            "detach": True,
            "network_mode": "none",
            "read_only": True,
            "mem_limit": MEMORY_LIMIT_BYTES,
            "cpu_period": CPU_PERIOD,
            "cpu_quota": CPU_QUOTA,
            "pids_limit": 64,
            "user": NON_ROOT_USER,
            "cap_drop": ["ALL"],
            "security_opt": ["no-new-privileges"],
            "environment": {
                "HOME": "/nonexistent",
                "PYTHONDONTWRITEBYTECODE": "1",
                "PYTHONUNBUFFERED": "1",
            },
            "stdin_open": False,
            "tty": False,
            "volumes": {},
        }

    def _wait_for_exit(self, container: Any, timeout: int) -> tuple[int, bool]:
        deadline = self._clock() + timeout

        while self._clock() < deadline:
            state = container.inspect().get("State", {})
            is_running = (
                state.get("Running") is True
                or str(state.get("Status", "")).lower()
                in {"created", "running", "restarting"}
            )
            if not is_running:
                return int(state.get("ExitCode", 125)), False

            remaining = max(0.01, deadline - self._clock())
            self._sleeper(min(0.1, remaining))

        try:
            container.kill()
        except Exception:
            pass
        return 124, True

    def _read_logs(self, container: Any) -> tuple[str, str]:
        try:
            stdout = as_text(container.logs(stdout=True, stderr=False))
        except Exception:
            stdout = ""

        try:
            stderr = as_text(container.logs(stdout=False, stderr=True))
        except Exception as error:
            stderr = f"Log retrieval failed: {safe_error(error)}"

        return stdout, stderr

    def _build_reusable_image(self, client: Any, code: str) -> None:
        context = Path(tempfile.mkdtemp(prefix="student-sandbox-build-"))
        try:
            (context / "app.py").write_text(code, encoding="utf-8")
            (context / "Dockerfile").write_text(self._dockerfile(), encoding="utf-8")

            build_result = client.images.build(
                path=str(context),
                tag=REUSABLE_IMAGE,
                rm=True,
                forcerm=True,
            )
            if isinstance(build_result, tuple) and len(build_result) == 2:
                logs = build_result[1]
                if logs is not None:
                    for _ in logs:
                        pass
        finally:
            shutil.rmtree(context, ignore_errors=True)

    @staticmethod
    def _dockerfile() -> str:
        return f"""FROM {BASE_IMAGE}
WORKDIR /app
COPY --chown=65532:65532 app.py /app/app.py
USER {NON_ROOT_USER}
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
CMD ["python", "-I", "-B", "/app/app.py"]
"""


def run(code: str, timeout: int = 20) -> RunResult:
    return PodmanCodeRunner().run(code, timeout)


def print_result(label: str, result: RunResult) -> None:
    print(f"\n{label}")
    print(result.model_dump_json(indent=2))


def demo() -> None:
    runner = PodmanCodeRunner()

    smoke = runner.run("import math\nprint(math.factorial(10))")
    print_result("Smoke test", smoke)

    failure = runner.run("raise RuntimeError('intentional demonstration failure')")
    print_result("Failure test", failure)

    timeout = runner.run("while True:\n    pass", timeout=10)
    print_result("Timeout test", timeout)

    if smoke.success:
        print(f"\nReusable image created: {REUSABLE_IMAGE}")
        print(f"Run it with: podman run --rm {REUSABLE_IMAGE}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--demo",
        action="store_true",
        help="Run smoke, failure, timeout, and image-build demonstrations.",
    )
    args = parser.parse_args()

    if not args.demo:
        parser.error("Use --demo.")
    demo()


if __name__ == "__main__":
    main()
